################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../usb/hw_config.c \
../usb/usb_desc.c \
../usb/usb_endp.c \
../usb/usb_istr.c \
../usb/usb_prop.c \
../usb/usb_pwr.c 

OBJS += \
./usb/hw_config.o \
./usb/usb_desc.o \
./usb/usb_endp.o \
./usb/usb_istr.o \
./usb/usb_prop.o \
./usb/usb_pwr.o 

C_DEPS += \
./usb/hw_config.d \
./usb/usb_desc.d \
./usb/usb_endp.d \
./usb/usb_istr.d \
./usb/usb_prop.d \
./usb/usb_pwr.d 


# Each subdirectory must supply rules for building sources it contributes
usb/hw_config.o: ../usb/hw_config.c usb/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F10X_MD -DUSE_STDPERIPH_DRIVER -D__ASSEMBLY__ -D_GRBL_ -DSTM32F103C8T6 -DLEDBLINK -DUSEUSB -DSTM32F103C8 -c -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/inc" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/src" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/stm_usb_fs_lib" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/usb" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/util" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/CMSIS/Device/ST/STM32F10x" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/CMSIS/Device/ST/STM32F10x/Include" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/CMSIS/Include" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/STM32F10x_StdPeriph_Driver" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/STM32F10x_StdPeriph_Driver/inc" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/STM32F10x_StdPeriph_Driver/src" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/stm_usb_fs_lib/inc" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/stm_usb_fs_lib/src" -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"usb/hw_config.d" -MT"$@"  -mfloat-abi=soft -mthumb -o "$@"
usb/usb_desc.o: ../usb/usb_desc.c usb/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F10X_MD -DUSE_STDPERIPH_DRIVER -D__ASSEMBLY__ -D_GRBL_ -DSTM32F103C8T6 -DLEDBLINK -DUSEUSB -DSTM32F103C8 -c -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/inc" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/src" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/stm_usb_fs_lib" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/usb" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/util" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/CMSIS/Device/ST/STM32F10x" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/CMSIS/Device/ST/STM32F10x/Include" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/CMSIS/Include" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/STM32F10x_StdPeriph_Driver" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/STM32F10x_StdPeriph_Driver/inc" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/STM32F10x_StdPeriph_Driver/src" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/stm_usb_fs_lib/inc" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/stm_usb_fs_lib/src" -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"usb/usb_desc.d" -MT"$@"  -mfloat-abi=soft -mthumb -o "$@"
usb/usb_endp.o: ../usb/usb_endp.c usb/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F10X_MD -DUSE_STDPERIPH_DRIVER -D__ASSEMBLY__ -D_GRBL_ -DSTM32F103C8T6 -DLEDBLINK -DUSEUSB -DSTM32F103C8 -c -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/inc" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/src" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/stm_usb_fs_lib" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/usb" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/util" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/CMSIS/Device/ST/STM32F10x" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/CMSIS/Device/ST/STM32F10x/Include" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/CMSIS/Include" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/STM32F10x_StdPeriph_Driver" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/STM32F10x_StdPeriph_Driver/inc" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/STM32F10x_StdPeriph_Driver/src" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/stm_usb_fs_lib/inc" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/stm_usb_fs_lib/src" -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"usb/usb_endp.d" -MT"$@"  -mfloat-abi=soft -mthumb -o "$@"
usb/usb_istr.o: ../usb/usb_istr.c usb/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F10X_MD -DUSE_STDPERIPH_DRIVER -D__ASSEMBLY__ -D_GRBL_ -DSTM32F103C8T6 -DLEDBLINK -DUSEUSB -DSTM32F103C8 -c -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/inc" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/src" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/stm_usb_fs_lib" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/usb" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/util" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/CMSIS/Device/ST/STM32F10x" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/CMSIS/Device/ST/STM32F10x/Include" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/CMSIS/Include" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/STM32F10x_StdPeriph_Driver" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/STM32F10x_StdPeriph_Driver/inc" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/STM32F10x_StdPeriph_Driver/src" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/stm_usb_fs_lib/inc" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/stm_usb_fs_lib/src" -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"usb/usb_istr.d" -MT"$@"  -mfloat-abi=soft -mthumb -o "$@"
usb/usb_prop.o: ../usb/usb_prop.c usb/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F10X_MD -DUSE_STDPERIPH_DRIVER -D__ASSEMBLY__ -D_GRBL_ -DSTM32F103C8T6 -DLEDBLINK -DUSEUSB -DSTM32F103C8 -c -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/inc" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/src" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/stm_usb_fs_lib" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/usb" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/util" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/CMSIS/Device/ST/STM32F10x" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/CMSIS/Device/ST/STM32F10x/Include" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/CMSIS/Include" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/STM32F10x_StdPeriph_Driver" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/STM32F10x_StdPeriph_Driver/inc" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/STM32F10x_StdPeriph_Driver/src" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/stm_usb_fs_lib/inc" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/stm_usb_fs_lib/src" -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"usb/usb_prop.d" -MT"$@"  -mfloat-abi=soft -mthumb -o "$@"
usb/usb_pwr.o: ../usb/usb_pwr.c usb/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F10X_MD -DUSE_STDPERIPH_DRIVER -D__ASSEMBLY__ -D_GRBL_ -DSTM32F103C8T6 -DLEDBLINK -DUSEUSB -DSTM32F103C8 -c -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/inc" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/src" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/stm_usb_fs_lib" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/usb" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/util" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/CMSIS/Device/ST/STM32F10x" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/CMSIS/Device/ST/STM32F10x/Include" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/CMSIS/Include" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/STM32F10x_StdPeriph_Driver" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/STM32F10x_StdPeriph_Driver/inc" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/Libraries/STM32F10x_StdPeriph_Driver/src" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/stm_usb_fs_lib/inc" -I"C:/Users/Abdullah/Desktop/GitHub/STM32_IDE/stm32grbl12/stm_usb_fs_lib/src" -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"usb/usb_pwr.d" -MT"$@"  -mfloat-abi=soft -mthumb -o "$@"

